made some changes to e2e test

diff --git a/.github/workflows/ci-cd_yt-etl.yaml b/.github/workflows/ci-cd_yt-etl.yaml
--- a/.github/workflows/ci-cd_yt-etl.yaml
+++ b/.github/workflows/ci-cd_yt-etl.yaml
@@ -89,9 +89,12 @@ jobs:
         - name: Run End-to-End DAG Tests
           if: steps.changed-files-tests.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
           run: |
+            set -e  # stop workflow if any DAG fails
             DAG_NAMES=("produce_json" "update_db" "data_quality")
+            RUN_DATE=$(date +"%Y-%m-%d")
             for DAG in "${DAG_NAMES[@]}"; do 
-              docker exec -t airflow-worker sh -c "airflow dags test $DAG"
+              echo "🔄 Testing DAG: $DAG"
+              docker exec -t airflow-worker sh -c "airflow dags test $DAG $RUN_DATE"
             done
         - name: Tear down Docker Compose
           if: steps.changed-files-tests.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
